import type { Statement, Transaction, ImportReview, DuplicatePair } from '@/lib/types/transaction'

// Sample Singapore bank statements
export const mockStatements: Statement[] = [
    {
        id: 'stmt-001',
        bankName: 'DBS',
        accountLabel: 'Visa ending 1234',
        periodStart: '2025-11-01',
        periodEnd: '2025-11-30',
        currency: 'SGD',
        transactionCount: 142,
        status: 'ingested',
        fileHash: 'abc123',
        createdAt: '2025-11-25T10:00:00Z',
    },
    {
        id: 'stmt-002',
        bankName: 'POSB',
        accountLabel: 'Savings ending 5678',
        periodStart: '2025-10-01',
        periodEnd: '2025-10-31',
        currency: 'SGD',
        transactionCount: 98,
        status: 'ingested',
        fileHash: 'def456',
        createdAt: '2025-10-28T14:30:00Z',
    },
    {
        id: 'stmt-003',
        bankName: 'UOB',
        accountLabel: 'One Card ending 9012',
        periodStart: '2025-09-01',
        periodEnd: '2025-09-30',
        currency: 'SGD',
        transactionCount: 76,
        status: 'ingested',
        fileHash: 'ghi789',
        createdAt: '2025-09-30T09:15:00Z',
    },
]

// Sample transactions for November 2025
export const mockTransactions: Transaction[] = [
    {
        id: 'txn-001',
        date: '2025-11-30',
        description: 'NETS QR NTUC FAIRPRICE XTRA',
        amount: -45.20,
        currency: 'SGD',
        source: 'DBS',
        monthBucket: '2025-11',
        transactionIdentifier: 'txn-id-001',
        statementId: 'stmt-001',
        createdAt: '2025-11-30T12:00:00Z',
    },
    {
        id: 'txn-002',
        date: '2025-11-29',
        description: 'GRAB *GRABPAY TOPUP',
        amount: -50.00,
        currency: 'SGD',
        source: 'POSB',
        monthBucket: '2025-11',
        transactionIdentifier: 'txn-id-002',
        statementId: 'stmt-002',
        createdAt: '2025-11-29T19:45:00Z',
    },
    {
        id: 'txn-003',
        date: '2025-11-29',
        description: 'GRAB *GRABTAXI SGP',
        amount: -10.50,
        currency: 'SGD',
        source: 'DBS',
        monthBucket: '2025-11',
        transactionIdentifier: 'txn-id-003',
        statementId: 'stmt-001',
        createdAt: '2025-11-29T08:30:00Z',
    },
    {
        id: 'txn-004',
        date: '2025-11-28',
        description: 'SHOPEE *ORDER 839201842',
        amount: -23.90,
        currency: 'SGD',
        source: 'DBS',
        monthBucket: '2025-11',
        transactionIdentifier: 'txn-id-004',
        statementId: 'stmt-001',
        createdAt: '2025-11-28T14:20:00Z',
    },
    {
        id: 'txn-005',
        date: '2025-11-27',
        description: 'SALARY CREDIT',
        amount: 5500.00,
        currency: 'SGD',
        source: 'POSB',
        monthBucket: '2025-11',
        transactionIdentifier: 'txn-id-005',
        statementId: 'stmt-002',
        createdAt: '2025-11-27T10:00:00Z',
    },
    {
        id: 'txn-006',
        date: '2025-11-26',
        description: 'COLD STORAGE GREAT WORLD',
        amount: -67.80,
        currency: 'SGD',
        source: 'DBS',
        monthBucket: '2025-11',
        transactionIdentifier: 'txn-id-006',
        statementId: 'stmt-001',
        createdAt: '2025-11-26T18:15:00Z',
    },
    {
        id: 'txn-007',
        date: '2025-11-25',
        description: 'STARBUCKS MARINA BAY',
        amount: -12.40,
        currency: 'SGD',
        source: 'DBS',
        monthBucket: '2025-11',
        transactionIdentifier: 'txn-id-007',
        statementId: 'stmt-001',
        createdAt: '2025-11-25T09:30:00Z',
    },
    {
        id: 'txn-008',
        date: '2025-11-24',
        description: 'SPOTIFY PREMIUM',
        amount: -14.98,
        currency: 'SGD',
        source: 'DBS',
        monthBucket: '2025-11',
        transactionIdentifier: 'txn-id-008',
        statementId: 'stmt-001',
        createdAt: '2025-11-24T00:00:00Z',
    },
    {
        id: 'txn-009',
        date: '2025-11-23',
        description: 'HAWKER MAXWELL FOOD CTR',
        amount: -8.50,
        currency: 'SGD',
        source: 'DBS',
        monthBucket: '2025-11',
        transactionIdentifier: 'txn-id-009',
        statementId: 'stmt-001',
        createdAt: '2025-11-23T12:45:00Z',
    },
    {
        id: 'txn-010',
        date: '2025-11-22',
        description: 'NETFLIX.COM',
        amount: -15.98,
        currency: 'SGD',
        source: 'DBS',
        monthBucket: '2025-11',
        transactionIdentifier: 'txn-id-010',
        statementId: 'stmt-001',
        createdAt: '2025-11-22T00:00:00Z',
    },
]

// Mock import review data (for testing the review flow)
export function generateMockImportReview(statementId: string): ImportReview {
    const newTransactions: Transaction[] = [
        {
            id: 'new-001',
            date: '2025-12-01',
            description: 'GRAB *GRABTAXI SGP',
            amount: -12.50,
            currency: 'SGD',
            source: 'DBS',
            monthBucket: '2025-12',
            transactionIdentifier: 'new-txn-id-001',
            statementId,
            createdAt: new Date().toISOString(),
        },
        {
            id: 'new-002',
            date: '2025-12-01',
            description: 'NTUC FAIRPRICE TAMPINES',
            amount: -34.20,
            currency: 'SGD',
            source: 'DBS',
            monthBucket: '2025-12',
            transactionIdentifier: 'new-txn-id-002',
            statementId,
            createdAt: new Date().toISOString(),
        },
        {
            id: 'new-003',
            date: '2025-12-02',
            description: 'SHOPEE *ORDER 123456789',
            amount: -89.90,
            currency: 'SGD',
            source: 'DBS',
            monthBucket: '2025-12',
            transactionIdentifier: 'new-txn-id-003',
            statementId,
            createdAt: new Date().toISOString(),
        },
        {
            id: 'new-004',
            date: '2025-12-03',
            description: 'TOAST BOX SUNTEC CITY',
            amount: -6.80,
            currency: 'SGD',
            source: 'DBS',
            monthBucket: '2025-12',
            transactionIdentifier: 'new-txn-id-004',
            statementId,
            createdAt: new Date().toISOString(),
        },
        {
            id: 'new-005',
            date: '2025-12-04',
            description: 'GONG CHA BUGIS JUNCTION',
            amount: -5.90,
            currency: 'SGD',
            source: 'DBS',
            monthBucket: '2025-12',
            transactionIdentifier: 'new-txn-id-005',
            statementId,
            createdAt: new Date().toISOString(),
        },
    ]

    const duplicates: DuplicatePair[] = [
        {
            existing: mockTransactions[0], // NTUC from Nov
            new: {
                id: 'dup-new-001',
                date: '2025-11-30',
                description: 'NETS QR NTUC FAIRPRICE XTRA',
                amount: -45.20,
                currency: 'SGD',
                source: 'DBS',
                monthBucket: '2025-11',
                transactionIdentifier: 'txn-id-001', // Same identifier
                statementId,
                createdAt: new Date().toISOString(),
            },
            importId: 'import-dup-001',
        },
        {
            existing: mockTransactions[2], // Grab taxi from Nov 29
            new: {
                id: 'dup-new-002',
                date: '2025-11-29',
                description: 'GRAB *GRABTAXI SGP',
                amount: -10.50,
                currency: 'SGD',
                source: 'DBS',
                monthBucket: '2025-11',
                transactionIdentifier: 'txn-id-003', // Same identifier
                statementId,
                createdAt: new Date().toISOString(),
            },
            importId: 'import-dup-002',
        },
    ]

    return {
        statement: {
            id: statementId,
            bankName: 'DBS',
            accountLabel: 'Visa ending 1234',
            periodStart: '2025-12-01',
            periodEnd: '2025-12-05',
            currency: 'SGD',
            transactionCount: newTransactions.length + duplicates.length,
            status: 'reviewing',
            fileHash: 'xyz999',
            createdAt: new Date().toISOString(),
        },
        newTransactions,
        duplicates,
    }
}

// Get available months from transactions
export function getAvailableMonths(): string[] {
    const months = new Set(mockTransactions.map(t => t.monthBucket))
    return Array.from(months).sort().reverse()
}
